# Generated by Django 3.1 on 2020-11-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_site', '0001_initial'),
        ('sale_clothes', '0009_auto_20201107_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldata',
            name='user_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management_site.usersite'),
        ),
    ]
